# Generated by Django 4.2.30 on 2026-05-19 06:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('empresa', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ReporteSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completo_rutina', models.BooleanField(default=True)),
                ('nivel_energia', models.CharField(choices=[('Muy bajo', 'Muy bajo'), ('Bajo', 'Bajo'), ('Normal', 'Normal'), ('Bueno', 'Bueno'), ('Excelente', 'Excelente')], default='Bueno', max_length=20)),
                ('dolor', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Fuerte', 'Fuerte')], default='Ninguno', max_length=20)),
                ('satisfaccion', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de sesión',
                'verbose_name_plural': 'Reportes de sesión',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, default='', max_length=150)),
                ('frecuencia_pausas', models.CharField(choices=[('Cada 30 min', 'Cada 30 min'), ('Cada 45 min', 'Cada 45 min'), ('Cada 60 min', 'Cada 60 min'), ('Cada 90 min', 'Cada 90 min')], default='Cada 60 min', max_length=20)),
                ('nivel_actividad', models.CharField(choices=[('Sedentario', 'Sedentario'), ('Ligero', 'Ligero'), ('Moderado', 'Moderado'), ('Activo', 'Activo')], default='Moderado', max_length=20)),
                ('notificaciones', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
