# Generated by Django 4.2.30 on 2026-05-23 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveSmallIntegerField(help_text='Duración en minutos')),
                ('icono', models.CharField(choices=[('accessibility_new', 'Estiramiento'), ('rotate_right', 'Rotación'), ('self_improvement', 'Relajación'), ('directions_walk', 'Caminata'), ('pan_tool', 'Muñecas'), ('fitness_center', 'Fuerza'), ('sports_gymnastics', 'Gimnasia'), ('airline_seat_recline', 'Postura'), ('favorite', 'Bienestar'), ('psychology', 'Mental')], default='accessibility_new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['-created_at'],
            },
        ),
    ]
